// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaA92QMmEVLB3lO0UlK_6aPf-2lrIqpmA',
    appId: '1:165045898440:web:386b886278baae9d68a9fd',
    messagingSenderId: '165045898440',
    projectId: 'autow-md',
    authDomain: 'autow-md.firebaseapp.com',
    storageBucket: 'autow-md.appspot.com',
    measurementId: 'G-3TJPR2B75C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACqsNWlZxGIDt5qA-icrfSAr-LJAEX0gM',
    appId: '1:165045898440:android:a3e5457a7a48b02e68a9fd',
    messagingSenderId: '165045898440',
    projectId: 'autow-md',
    storageBucket: 'autow-md.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASsRIYFZUBEZVZUKu-gu5M1pzTWVYKjQo',
    appId: '1:165045898440:ios:13952dcc18c6de7168a9fd',
    messagingSenderId: '165045898440',
    projectId: 'autow-md',
    storageBucket: 'autow-md.appspot.com',
    iosClientId: '165045898440-oummv765qgt6m3bsh3a2bjescrbgj0gp.apps.googleusercontent.com',
    iosBundleId: 'com.userapps.autow',
  );
}
